### ISSUE TITLE
Token based auth

### ISSUE THREAD

**Issue by LKay** [funcool/buddy#15] opened 2014-11-14 02:36 UTC
I tried to implement token based auth in my application but the token-backend does not work for some reason.

I set up backend and handlers according to docs:

    (defn authenticate
      [req auth-data]
      "test")

    (def auth-backend
      (token-backend {:authfn authenticate
                      :unauthorized-handler unauthorized-handler}))

And my request handler looks like:

    (def api
      (->
        (handler/api api-routes)
        (wrap-authentication auth/auth-backend)
        (wrap-authorization auth/auth-backend)
        (wrap-session)
        (wrap-restful-response)))

The method ``authfn`` gets never called and I can't authenticate user in any way using buddy. Is this backend broken?

**Comment by Arcanum-XIII** [comment] 2015-01-10 14:00
I'm trying to wrap my head around the token backend (unsigned for now), with the stable version and it's working fine. I don't use the wrap-authorization, since I'm using it with liberator for authorization. 

The auth function was never called till I got the proper header though, which make take the form of : "authorization:Token token". Otherwise no game !

**Comment by Arcanum-XIII** [comment] 2015-01-11 16:13
Addendum : seem that 3.0-SNAPSHOT doesn't call the authfn.

**Comment by niwibe** [comment] 2015-01-11 16:22
`authfn` is called by the backend the `authenticate` function is called. And `authenticate` function is only called when parse returns a not response and not nil value: https://github.com/funcool/buddy-auth/blob/master/src/clojure/buddy/auth/middleware.clj#L32

I think, that everything works as expected.
I closing this issue.

**Closed by niwibe** 2015-01-11 16:22 UTC

**Comment by Arcanum-XIII** [comment] 2015-01-12 09:34
@niwibe after double checking my code : yes, you're right. A typo, and some confusing behavior in lein ring headless push me into it. 
So, everything is working as intended for me, be it signed-token or plain token.

**Comment by niwibe** [comment] 2015-01-12 09:39
Great! Thanks!
